# Site settings
title: Paul Johnson
email: paul.johnson@sheffield.ac.uk

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ptwiddle
github_username:  ptwiddle
# Build settings
markdown: kramdown
